language: python
python:
  - "2.7"
  - "3.3"

install:
  - pip install .
  - pip install requests --use-mirrors
  - pip install requests-oauthlib --use-mirrors
  - pip install fasteners --use-mirrors
  - pip install coveralls --use-mirrors

script:
  - make coverage

after_success:
  - coveralls
