language: python
python:
- '2.7'
- '3.4'
install:
- pip install -r requirements/base.txt
- pip install -r requirements/development.txt
script: nosetests
sudo: required
dist: precise
deploy:
  provider: pypi
  user: "$USER"
  password: "$PASS"
  on:
    distributions: sdist bdist_wheel
    repo: Mangopay/mangopay2-python-sdk
    branch: release
    tags: false
    condition: $TRAVIS_PYTHON_VERSION = "3.4"
env:
  global:
  - secure: ozYaIxo31l/rUclVX+XWgpZzJwF6txu3FGeBFh5NOAbi8BB1FWjBvH9cyyv0j3JcnQokLqaOMqyCGCIxTV9cCZxqJB1M8BvHtJpcXX9ZZGJxWWdU67b5o+zOppHlUlQl38A9i1ZIYCd5inLdad6+GHloy93Gydi7g1UlK7JHo24=
  - secure: B3b0U7wMBnxMXtTeTIO+JpV3ytzGqPEkF1v6p49OwGIQFNcQFn+j44C4SM9lGpE33UG3W4oCB9aCeFI52QpyNUGOXJig0lw18A57DeojRC0N5zBgwroJxTylpraUwIpj1JTpaQTYspxT88qyyUDLJTD8dAcLvLAaB3M21cl3G5g=
  - secure: IN2d1ckD0zw8onL5jnMkNPm9eYzsyYV6tYabZ4CvbtAr4Obk463b9Ux+pmGCB57Iu2AK9+hwnO+u1r9cQPFncU79BNxfvfsiQ74K+6r58ljmL560enruZszOpx/u4WGqWHaAWB/3jgKfJWp8CqbEWRZRfg2tDOGaJyo1Kw/nNas=
  - secure: AVrwOAgSWS2cYMYw0Y7m9VhB9iHlB7NvbZ4bulSYmNt8JBzwoxin0Kdsr2++ZG29eEG47HpGncitPb+FSYql/iFy4RxVJMb/IidAXokX993oq3XXTdWwRVgo0ekKenKoVgwMqBZnD74ndmRVMclYokHmVC+Jhi6FpUMnygg7dkg=
